### ISSUE TITLE
Inserts multiple anchor points for headers with the same text

### ISSUE THREAD

**Issue by dashaluna** [dashaluna/hm-content-toc#29]
![screen shot 2015-05-11 at 14 02 33](https://cloud.githubusercontent.com/assets/2185972/7565285/c71949ca-f7e6-11e4-8b77-3e45a8089045.png)

**Comment by dashaluna** [comment]
Use regex lookbehind http://www.regular-expressions.info/lookaround.html

Example `(?<!<\/a>)<h2>Header 2<\/h2>` Perhaps add some attribute at the end of the closing `>` of the anchor to make sure we're matching our anchor and not some link. Lookbehinds don't work with quantifiers so can't use `.*?`

**Comment by roborourke** [comment]
If you have multiple items in your matches with the same value could you add a numeric ID to them as well to differentiate them?

**Comment by dashaluna** [comment]
@sanchothefat sorry I don't understand :( The TOC list is generated correctly. However, when we insert anchors before the headers in the content itself... and the headers are identical, then the anchor is inserted as many times as that header appears in content. Does that make sense?

This is due to this regex here https://github.com/dashaluna/hm-content-toc/blob/master/includes/class-content-toc.php#L259

Perhaps I need to make regex to match the first match, not global and also add the look behind to check that a link has been inserted already..

**Comment by tcrsavage** [comment]
Something like this is probably the easiest fix:

```
$anchors = array();

foreach ( $matches as $key => $match_set ) {

    // Counter of matched headers, starting at 1
    $key_current      = $key + 1;

    //Store all anchors so we can ensure we don't insert multiple anchors for duplicate headers
    $anchors[] = sprintf(
        '<a name="heading-%s"%s></a>%s',
        esc_attr( $key_current ),
        $this->tag_class( $this->settings['anchor_class'] ),
        $match_set[0]
    );

    // Add anchor just before the matched header element
    // Use negative lookbehind to ensure we don't tag multiple anchors to a single header
    $content = preg_replace(
        '/(?<!' . implode( '|', array_map( 'preg_quote', $anchors ) ) . ')'  . preg_quote( $match_set[0], '/' ) . '/',
        $anchors[ ( count( $anchors ) - 1 ) ],
        $content,
        1 //maximum replacements
    );
}
```

**Comment by dashaluna** [comment]
Ideas are welcome for more elegant solution if anyone has got them ;)
