### ISSUE TITLE
Add README file

### ISSUE THREAD

**Issue by dashaluna** [dashaluna/hm-content-toc#33]

**Comment by tcrsavage** [comment]
Author,
Title,
Description,
Version,
URL,
Installation/Use instructions,
Changelog,

**Comment by dashaluna** [comment]
**Resources**
- [Pippin Plugins - on readme.txt](https://pippinsplugins.com/how-to-properly-format-and-enhance-your-plugins-readme-txt-file-for-the-wordpress-org-repository/)
- [WP Plugin dev FAQ](https://wordpress.org/plugins/about/faq/)
- [WP example of readme file](https://wordpress.org/plugins/about/readme.txt)
- [WP Readme Validator](https://wordpress.org/plugins/about/validator/)

**Comment by dashaluna** [comment]
WP example https://wordpress.org/plugins/about/readme.txt

**Comment by dashaluna** [comment]
[Plugin dev FAQ](https://wordpress.org/plugins/about/faq/)
Also [Readme Validator](https://wordpress.org/plugins/about/validator/)

**Comment by dashaluna** [comment]
Convert WP readme markdown into Github markdown
https://github.com/benbalter/WP-Readme-to-Github-Markdown

**Comment by dashaluna** [comment]
Travis:
[![Build Status](https://travis-ci.org/dashaluna/hm-content-toc.svg?branch=master)](https://travis-ci.org/dashaluna/hm-content-toc)

**Comment by dashaluna** [comment]
To generate `.md` file from `.txt` file, I'm using https://github.com/benbalter/WP-Readme-to-Github-Markdown

Run the command from the root plugin directory
`./vendor/bin/wp2md convert -i readme.txt -o README.md`
